export const SET_FILTER_CATEGORY_USER   = 'SET_FILTER_CATEGORY_USER'
export const SET_FILTER_COLOR_USER      = 'SET_FILTER_COLOR_USER'
export const SET_FILTER_SIZE_USER       = 'SET_FILTER_SIZE_USER'
export const SET_FILTER_SEARCH_USER     = 'SET_FILTER_SEARCH_USER'